version: 0.2

env:
  variables:
    S3_BUCKET_NAME: "builddb"
    GAME_NAME: "tictactoe"
    EXECUTABLE_NAME: "${GAME_NAME}-executable.exe"
    S3_UPLOAD_PATH: "game/${EXECUTABLE_NAME}"
    DOCKERHUB_USERNAME: "foxe03"
    DOCKERHUB_SECRET_ARN: "arn:aws:secretsmanager:us-east-1:339712721384:secret:docker-us-JYDQoe"

phases:
  install:
    runtime-versions:
      python: 3.8
      docker: 20
    commands:
      - pip install pyinstaller
      - pip install psycopg2-binary
      - powershell -Command "Install-PackageProvider -Name NuGet -Force -Scope CurrentUser"
      - powershell -Command "Install-Module -Name AWS.Tools.SecretsManager -Force -Scope CurrentUser"
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - $secrets = Get-SECSecretValue -SecretId ${DOCKERHUB_SECRET_ARN} | ConvertFrom-Json
      - docker login -u "${DOCKERHUB_USERNAME}" -p $secrets.SecretString.password
  build:
    commands:
      - pyinstaller --onefile --hidden-import=psycopg2 src/ui.py
      - docker build -t ${DOCKERHUB_USERNAME}/${GAME_NAME}:latest .
      - docker push ${DOCKERHUB_USERNAME}/${GAME_NAME}:latest
  post_build:
    commands:
      - echo "Listing all files in dist directory:"
      - dir dist
      - echo "Uploading executable to S3..."
      - aws s3 cp dist/ui.exe s3://${S3_BUCKET_NAME}/${S3_UPLOAD_PATH}
artifacts:
  files:
    - 'dist/*'
